version: 0.1

pipelines:
  ingest:
    - name: chunk_size_ingest
      script: chunk_size_experiment.py
      method: ingest
  query:
    - name: chunk_size_query
      script: chunk_size_experiment.py
      method: query
  cleanup:
    - name: chunk_size_cleanup
      script: chunk_size_experiment.py
      method: cleanup

recipes:
  - name: chunk_size_500
    ingest: chunk_size_ingest
    query: chunk_size_query
    cleanup: chunk_size_cleanup
    variables:
      - name: chunk_size
        value: 500
  - name: chunk_size_1000
    ingest: chunk_size_ingest
    query: chunk_size_query
    cleanup: chunk_size_cleanup
    variables:
      - name: chunk_size
        value: 1000

datasets:
  - blockchain_solana
  - braintrust_coda_help_desk

metrics:
  - groundedness
  - answer_correctness

eval_llm:
  - vendor: open_ai
    model: gpt3.5-turbo
