version: 0.1

pipelines:
  ingest:
    - name: standard_ingest
      script: standard_ingest.py
      variables:
        - name: chunk_size
          values: [250, 500, 1000]
  query:
    - name: standard_query
      script: standard_query.py
      framework: lang_chain
      variables:
        - name: k
          values: [2, 5]
        - name: llm
          values: ["open-ai gpt3.5-turbo", "vertex"]
    - name: vertext_query
      script: vertext_query.py


datasets:
  - blockchain_solana
  - uber10k

metrics:
  - groundedness
  - answer_correctness

eval_llm:
  - vendor: open_ai
    model: gpt3.5-turbo


# variables can be primitive types, or dict with primitive types

