version: 0.1

steps:
  ingest:
    - name: chunk_size_ingest
      script: chunk_size_experiment.py
      method: ingest
  query:
    - name: chunk_size_query
      script: chunk_size_experiment.py
      method: query
  cleanup:
    - name: chunk_size_cleanup
      script: chunk_size_experiment.py
      method: cleanup

recipes:
  - name: chunk_size_500
    ingest: chunk_size_ingest
    query: chunk_size_query
    cleanup: chunk_size_cleanup
    ingredients:
      - chunk_size: 500
  - name: chunk_size_1000
    ingest: chunk_size_ingest
    query: chunk_size_query
    cleanup: chunk_size_cleanup
    ingredients:
      - chunk_size: 1000


datasets:
  - name: blockchain_solana
    kind: llama
  - name: braintrust_coda_help_desk
    kind: llama

eval_llms:
  - vendor: open_ai
    model: gpt3.5-turbo
    name: gpt3.5
    default: true
  - name: llama3
    vendor: huggingface
    model: llama3

metrics:
  groundedness:
    enabled: true
  answer_correctness:
    enabled: true
    eval_llm: llama3